### ISSUE TITLE
"Percentage" positioning doesn't work on Firefox and IE when initial page scroll is not 0

### ISSUE THREAD

**Issue by szczepankrol-loop** [dixonandmoe/rellax#53] opened 2017-04-12 12:13 UTC
First of all - thanks for a wonderfull library!

While developing on Chrome everything worked perfectly but then, when I tried to run the project on Firefox or IE an issue came up.

I'm using "center: true" setting and it seems that it calculates the positions correctly only if the page is loaded while beeing on top of the page.
If I'm somewhere lower on the page and hit refresh button - the positions are completely miscalculated.

It's easy to reproduce by running one of the tests - 'tests/percentage.html' - on Firefox, scrolling down a bit and hitting "F5".

Please let me know what can I do to fix this issue.
Currently - it completely brakes my project and if it's an unfixable issue - I'll have to resign from using rellax (which I would not like to).

Thanks!

**Comment by p-realinho** [comment] 2017-04-18 23:22
Hi, thanks for using Rellax :)

I can't seem to replicate this issue.
What versions of Firefox and IE are you testing on?

**Comment by szczepankrol-loop** [comment] 2017-04-19 10:14
Firefox: 52.0.2 (32-bit)
IE: 11.0.24

Here are the screenshots of the issue:

1. I open the page, scroll down and it behaves correctly:
![correct--scrolled-down-from-top](https://cloud.githubusercontent.com/assets/25029316/25175054/9a3ea7b4-24f9-11e7-8c96-634e1fa56167.png)

2. Then I refresh the page (F5) and the light element jumps down
![incorrect--refreshed-after-scrolled-down](https://cloud.githubusercontent.com/assets/25029316/25175074/b15ad60c-24f9-11e7-9815-67f9c05530df.png)

Thanks for your help!

**Comment by p-realinho** [comment] 2017-04-21 22:11
I swear I'd love to help you, but I still cannot replicate this. Sorry :/

Still, I'll try to see if there's any compatibility issues with the code that's supposed to prevent this problem.
I'll keep you posted if I find something ...

**Comment by timhettler** [comment] 2017-05-03 21:58
I can reproduce this issue (in Chrome, no less). @p-realinho The reason you can't reproduce it is because the it's fixed in the latest version of the library. You have to make a new release (with a new version number, see issue #45) so that users get your latest code. NPM caches the code, and won't fetch a new copy unless the version number changes.

I'm happy to walk you through this if you need help; just @ me and we can get in touch.

**Comment by p-realinho** [comment] 2017-05-08 00:24
@timhettler Oh, I see ... I wasn't aware that the NPM version was behind this one.
Thank you for your help!
I think I'll leave that to @moeamaya maybe?

**Comment by p-realinho** [comment] 2017-08-02 21:17
Hi @szczepankrol-loop 
The repo was just updated to v1.1 both in NPM and Bower.
Could you please check if the problem still persists, or if this issue can be closed?
Thanks :)

**Comment by moeamaya** [comment] 2017-08-29 01:23
Thanks @p-realinho. Should be fixed now with the NPM/Bower updated!

**Closed by moeamaya** 2017-08-29 01:23 UTC
